config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root 'addresses#index'

  get '/ping', to: 'main#ping', as: 'ping'
  get '/filter', to: 'main#filter', as: 'filter'
  post '/data_request', to: 'main#data_request', as: 'data_request'

  resources :addresses

  mount Resque::Server.new, at: "/resque"
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :testeds

  default_scope { order(id: :desc) }

  scope :only_working, -> () { where(deleted: false).where(switched: true) }

  scope :without_deleted, -> () { where(deleted: false) }

end

app/models/tested.rb
class Tested < ActiveRecord::Base
  belongs_to :address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :set_address, only: [ :edit, :update, :destroy ]

  def index
    @addresses = Address.without_deleted.page(params[:page])
  end

  def new
    @address = Address.new
  end

  def create
    address = Address.find_or_create_by(params[:address][:ip])
    address.update!(addresses_params)
    address.deleted = false
    address.save
    redirect_to addresses_path
  end

  def edit
  end

  def update
    @address.update!(addresses_params)
    redirect_to addresses_path
  end

  def destroy
    @address.deleted = true
    @address.save
    redirect_to addresses_path
  end

  private

  def addresses_params
    params.require(:address).permit( :name, :ip, :switched )
  end

  def set_address
    @address = Address.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def ping
    Resque.enqueue(Runner)
  end

  def filter
  end

  def data_request
    address = Address.where("ip = ?", params[:request][:ip])
    testeds_withnull = Tested.where(address: address)
                        .where("test_in > ?", params[:request][:from])
                        .where("test_in < ?", params[:request][:to])
    counts_withnull = testeds_withnull.count
    testeds = testeds_withnull.where("duration > 0").order(:duration)
    min = testeds.minimum(:duration)
    max = testeds.maximum(:duration)
    average = testeds.average(:duration)
    testeds_duration = testeds.map(&:duration)
    counts = testeds.count
    sigma = Math.sqrt(average)
    lost = 100 - ((counts * 100) / counts_withnull)
    if counts.even?
      median = (testeds_duration[counts/2 - 1] + testeds_duration[counts/2])/2
    else
      median = testeds_duration[(counts - 1) / 2]
    end

    @data_request = {min: min, max: max, average: average, median: median, sigma: sigma, lost: lost}

  end

  private

  def sigma

  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
  def tab_select(name, controller)
    'active' if name == controller
  end
end

app/views/addresses/_address.html.haml
%tr
  %td= address.id
  %td= link_to address.ip, edit_address_path(address)
  %td= address.switched
  %td= link_to :delete,
          address_path(address),
          :method => :delete,
          :data => { :confirm => 'Are you sure?' }

app/views/addresses/_address_title.html.haml
%tr
  %th #
  %th= :IP
  %th= :on
  %th

app/views/addresses/_form.html.haml
= form_for @address, html: { class: 'form-horizontal',role: 'form' } do |f|
  %div.form-group
    %label.col-sm-4.control-label{ for: "address_name" }
      Name
    %div.col-sm-8
      = f.text_field :name, class: 'form-control'
  %div.form-group
    %label.col-sm-4.control-label{ for: "address_ip" }
      IP
    %div.col-sm-8
      = f.text_field :ip, class: 'form-control'
  %div.form-group
    %label.col-sm-4.control-label{ for: "address_switched" }
      ON?
    %div.col-sm-8
      = f.check_box :switched
  %div.form-group
    %div.col-sm-offset-4.col-sm-8
      = link_to :exit, addresses_path, {class: "btn btn-danger button" }
      %button.btn.btn-default{ type: "submit button", class: "btn btn-info button" }
        = :submit

app/views/addresses/edit.html.haml
= render 'form'

app/views/addresses/index.html.haml
%h1
  = link_to :New, new_address_path
  {
  = link_to :ping, ping_path, remote: true
  }

%table.table.table-striped
  %thead
    = render 'address_title'
  %tbody.tbody-question
    = render @addresses

%br

= paginate @addresses, :theme => 'twitter-bootstrap-3',
                   :pagination_class => "pagination-sm"

%br

app/views/addresses/new.html.haml
= render 'form'

app/views/addresses/ping.js.erb
ok

app/views/layouts/_menu.html.haml
%nav{ class: 'navbar navbar-default navbar-fixed-top', role: 'navigation' }
  %div{ class: 'navbar-header'}
    %button.some{ type: 'button', class: 'navbar-toggle', 'data-toggle': 'collapse', 'data-target': '#bs-example-navbar-collapse-1' }
      %span{ class: 'sr-only' } Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.some{ href: root_path } На главную
  %div{ class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
    %ul.some{ class: 'nav navbar-nav'}
      %li{ class: tab_select('addresses', controller_name) }
        %a{ href: addresses_path } IP
      %li{ class: tab_select('main', controller_name) }
        %a{ href: filter_path } Запрос

app/views/layouts/application.html.haml
%html
  %head
    %title GenbankStaffTested
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %div.container-fluid
      %br
      %br
      %br
      %div.col-md-12
        = render 'layouts/menu'
        = yield

app/views/main/data_request.js.erb
$('.for-json').html('<%= @data_request.to_json %>');

app/views/main/filter.html.haml
= form_tag('data_request', remote: true, class: 'form-horizontal', role: 'form', method: "post") do
  %div.form-group
    %label.col-sm-4.control-label{ for: 'ip' }
      ip
    %div.col-sm-8
      = text_field(:request, :ip)
  %div.form-group
    %label.col-sm-4.control-label{ for: 'dateFrom' }
      from
    %div.col-sm-8
      = datetime_local_field(:request, :from)
  %div.form-group
    %label.col-sm-4.control-label{ for: 'dateTo' }
      to
    %div.col-sm-8
      = datetime_local_field(:request, :to)
  %div.form-group
    %div.col-sm-offset-4.col-sm-8
      = submit_tag("send")

%div.for-json